import assert from "node:assert/strict";
import fs from "node:fs/promises";
import { sidebarAction, closeSidebar } from "./sidebar_browser_helpers.mjs";
const { chromium } = await import(process.argv[2] ?? "playwright");
const origin = process.env.MIRA_SERVER_URL ?? "http://127.0.0.1:8787";
const ids = ["10000000-0000-4000-8000-000000000001", "10000000-0000-4000-8000-000000000002", "10000000-0000-4000-8000-000000000003"];
const rows = ids.map((threadId, index) => ({ threadId, title: ["Large conversation", "New conversation", "Unknown usage"][index],
  cwd: "/work", generation: 1, itemCount: 1, updatedAt: new Date().toISOString(),
  activity: { state: "idle", generation: 1, itemCount: 1 }, tokenUsage: index === 2 ? null :
    { inputTokens: index ? 0 : 125000, outputTokens: index ? 0 : 8000, cachedInputTokens: index ? 0 : 100000 } }));
const estimate = (amount, status = 'complete') => ({amount,status,pricingDate:'2026-09-06',breakdown:{input:amount/2,cached:amount/4,output:amount/4}});
rows[0].costEstimate = estimate(0.75); rows[0].model = 'gpt-6-astra';
rows[1].costEstimate = estimate(0); rows[2].costEstimate = {amount:null,status:'unavailable'};
const browser = await chromium.launch({ headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.route("**/v1/codex/threads?*", route => route.fulfill({ json: { data: rows } }));
  await context.route(/\/v1\/codex\/threads\/[^?]+\?/, route => {
    const path = new URL(route.request().url()).pathname, row = rows.find(row => path.includes(row.threadId));
    return route.fulfill({ json: path.endsWith("/transcript") ? { generation: row.generation, itemCount: row.itemCount,
      trace: [{ key: "message", kind: "assistant", body: "A persisted conversation.", sourceItemSeq: 1 }], nextCursor: null } : row });
  });
  const page = await context.newPage(), errors = [];
  page.setDefaultTimeout(15_000); page.on("pageerror", error => errors.push(error.message));
  await page.goto(origin);
  await page.locator("#password").fill(process.env.MIRA_TEST_ADMIN_PASSWORD ?? "mira-local-admin-password");
  await page.locator('#loginForm button[type="submit"]').click();
  await page.locator("#dashboardView:not(.hidden)").waitFor();
  await page.goto(`${origin}/?thread=${ids[0]}`);
  const summary = page.locator(`[data-thread-token-usage="${ids[0]}"]`);
  await summary.waitFor({ state: "visible" });
  assert.equal(await summary.textContent(), "125k in · 8k out");
  assert.match(await summary.getAttribute("title"), /缓存输入 100,000 Token/);
  assert.equal(await page.locator(`[data-thread-token-usage="${ids[1]}"]`).textContent(), "0 in · 0 out");
  assert.equal(await page.locator(`[data-thread-token-usage="${ids[2]}"]`).isVisible(), false);
  const row = page.locator(`[data-thread-row="${ids[0]}"]`);
  await page.waitForFunction(id => document.querySelector(`[data-thread-cost="${id}"]`)?.textContent === '≈$0.75', ids[0]);
  const height = (await row.boundingBox()).height;
  const button = row.locator('button[data-thread-id]'), menu = row.locator('.thread-menu-toggle');
  assert.equal((await button.boundingBox()).width, (await row.boundingBox()).width, 'the menu reserves no column');
  const beforeHover = await row.locator('strong').boundingBox();
  await row.hover();
  assert.equal(await menu.evaluate(element => getComputedStyle(element).position), 'absolute');
  assert.deepEqual(await row.locator('strong').boundingBox(), beforeHover, 'hover overlay does not reflow the title');
  assert.ok((await menu.boundingBox()).x > beforeHover.x && (await menu.boundingBox()).x < beforeHover.x + beforeHover.width);
  const resize = page.locator('#agentSidebarResize');
  const handle = await resize.boundingBox();
  await page.mouse.move(handle.x + 3, 300); await page.mouse.down(); await page.mouse.move(handle.x + 123, 300, {steps:8});
  assert.equal((await page.locator('#agentThreadDrawer').boundingBox()).width, 420, 'sidebar follows mouse while resizing');
  await page.mouse.up();
  assert.equal(await page.evaluate(() => localStorage.getItem('mira.sidebar.width')), '420');
  await page.reload(); await summary.waitFor({state:'visible'});
  assert.equal((await page.locator('#agentThreadDrawer').boundingBox()).width, 420, 'width survives reload');
  await resize.focus(); await page.keyboard.press('End');
  assert.equal((await page.locator('#agentThreadDrawer').boundingBox()).width, 480);
  await page.keyboard.press('Home');
  assert.equal((await page.locator('#agentThreadDrawer').boundingBox()).width, 240);
  assert.equal(await summary.isVisible(), true, 'narrow desktop keeps a compact token summary');
  assert.match(await summary.evaluate(element => getComputedStyle(element, '::after').content), /125k↑ 8k↓/);
  await page.keyboard.press('Shift+ArrowRight'); await page.keyboard.press('ArrowRight');
  assert.equal((await page.locator('#agentThreadDrawer').boundingBox()).width, 300);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);

  const panel = page.locator("#conversationDetails");
  const settled = () => panel.evaluate(element => Promise.all(element.getAnimations().map(animation => animation.finished.catch(() => {}))));
  const openDetails = async id => { await page.locator(`[data-thread-row="${id}"]`).hover(); await page.locator(`[data-thread-menu="${id}"]`).click(); await page.locator("#threadShowDetails").click(); await page.waitForFunction(() => document.querySelector("#conversationDetailsStatus")?.textContent === ""); await settled(); };
  await openDetails(ids[0]);
  const facts = page.locator("#conversationTokenUsageFacts");
  assert.deepEqual(await facts.locator("dd").allTextContents(), ["125,000", "100,000", "8,000"]);
  assert.match(await facts.textContent(), /含缓存/);
  assert.equal(await page.locator('#conversationCostAmount').textContent(), '≈ $0.75');
  assert.match(await page.locator('#conversationDetailsFacts').textContent(), /最近使用的模型gpt-6-astra/);
  assert.match(await page.locator('#conversationCostPricing').textContent(), /Standard.*2026-09-06/);
  // Metadata can change before the history count advances. Both views update in place.
  rows[0].costEstimate = estimate(1.5);
  rows[0].tokenUsage = { inputTokens: 250000, cachedInputTokens: 200000, outputTokens: 16000 };
  await page.waitForFunction(id => document.querySelector(`[data-thread-token-usage="${id}"]`)?.textContent === "250k in · 16k out", ids[0]);
  assert.deepEqual(await facts.locator("dd").allTextContents(), ["250,000", "200,000", "16,000"]);
  await page.waitForFunction(() => document.querySelector('#conversationCostAmount').textContent === '≈ $1.50');
  assert.equal((await row.boundingBox()).height, height, "usage stays on the existing second row");
  if (process.env.MIRA_WEB_SCREENSHOT_DIR) {
    await fs.mkdir(process.env.MIRA_WEB_SCREENSHOT_DIR, { recursive: true });
    await page.screenshot({ path: `${process.env.MIRA_WEB_SCREENSHOT_DIR}/thread-token-usage-desktop.png` });
  }
  await page.locator("#conversationDetailsClose").click();
  await openDetails(ids[1]);
  assert.equal(await page.locator('#conversationCostAmount').textContent(), '≈ $0.00');
  await page.locator('#conversationDetailsClose').click();
  await openDetails(ids[2]);
  assert.equal(await page.locator('#conversationCostAmount').textContent(), '暂无法估算');
  assert.deepEqual(await facts.locator("dd").allTextContents(), ["未提供", "未提供", "未提供"]);
  await page.locator("#conversationDetailsClose").click();
  // Replaced history must clear the old generation, even when counters decrease.
  rows[0].costEstimate = estimate(0.02, 'partial');
  rows[0].generation = 2; rows[0].tokenUsage = { inputTokens: 1000, cachedInputTokens: 0, outputTokens: 100 };
  await page.waitForFunction(id => document.querySelector(`[data-thread-token-usage="${id}"]`)?.textContent === "1k in · 100 out", ids[0]);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator("#agentThreadDrawerToggle").click();
  await summary.waitFor({ state: "visible" });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await sidebarAction(page, "agentThemeToggle");
  await openDetails(ids[0]);
  assert.deepEqual(await facts.locator("dd").allTextContents(), ["1,000", "0", "100"]);
  assert.equal(await page.locator('#conversationCostAmount').textContent(), '已估算部分 ≈ $0.02');
  if (process.env.MIRA_WEB_SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.MIRA_WEB_SCREENSHOT_DIR}/thread-token-usage-mobile.png` });
  await page.locator("#conversationDetailsClose").click();
  await page.setViewportSize({ width: 320, height: 844 });
  assert.equal(await summary.isVisible(), true, "overlay menus free enough width for usage even on narrow phones");
  assert.equal(await page.locator(`[data-thread-activity="${ids[0]}"]`).isVisible(), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await panel.waitFor({ state: "hidden" });
  await page.setViewportSize({ width: 390, height: 844 });
  await closeSidebar(page);
  await page.locator("#conversationInput").fill("Draft survives opening details");
  const toggle = page.locator("#conversationDetailsToggle");
  const openWithToggle = async () => { await toggle.click(); await panel.waitFor({ state: "visible" }); await settled(); };
  await openWithToggle();
  assert.equal(await toggle.getAttribute("aria-expanded"), "true");
  let bounds = await panel.boundingBox();
  assert.deepEqual([bounds.x, bounds.y, bounds.width, bounds.height], [50, 0, 340, 844], "mobile details fill the right edge at the same width as navigation");
  await page.keyboard.press("Tab");
  assert.equal(await page.evaluate(() => document.querySelector("#conversationDetails").contains(document.activeElement)), true, "modal drawer retains keyboard focus");
  await page.mouse.click(20, 400);
  await panel.waitFor({ state: "hidden" });
  assert.equal(await toggle.getAttribute("aria-expanded"), "false");
  await openWithToggle();
  await page.setViewportSize({ width: 1200, height: 900 });
  await page.waitForFunction(() => !document.querySelector("#conversationDetails").matches(":modal"));
  assert.equal(await panel.evaluate(element => element.matches(":modal")), false);
  bounds = await panel.boundingBox();
  const left = await page.locator("#agentThreadDrawer").boundingBox();
  assert.equal(bounds.width, left.width, "desktop navigation and details share the same width");
  const chat = await page.locator(".conversation-card").boundingBox();
  assert.ok(chat.x + chat.width <= bounds.x + 1, "desktop details reserve a separate column");
  assert.equal(await panel.evaluate(element => getComputedStyle(element).backgroundColor), await page.locator("#agentThreadDrawer").evaluate(element => getComputedStyle(element).backgroundColor));
  assert.equal(await page.locator(".thread-project-summary").first().evaluate(element => getComputedStyle(element).backgroundColor), "rgba(0, 0, 0, 0)", "project headers share the sidebar material");
  await toggle.click(); await panel.waitFor({ state: "hidden" });
  await page.setViewportSize({ width: 390, height: 844 });
  const session = await context.newCDPSession(page);
  await session.send("Emulation.setTouchEmulationEnabled", { enabled: true, maxTouchPoints: 5 });
  const touch = async (type, x, y = 700) => {
    await session.send("Input.dispatchTouchEvent", { type, touchPoints: x === undefined ? [] : [{ x, y, id: 0, radiusX: 2, radiusY: 2, force: 1 }] });
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(resolve)));
  };
  for (const x of [110, 20]) {
    await openWithToggle();
    await touch("touchStart", x);
    await touch("touchMove", x + 45);
    assert.ok(Math.abs((await panel.boundingBox()).x - 95) < 2, "right drawer follows a drag on content or backdrop");
    await touch("touchMove", x + 180);
    assert.ok(Math.abs((await panel.boundingBox()).x - 230) < 2, `drag from ${x}: ${JSON.stringify(await panel.boundingBox())}`);
    await touch("touchEnd"); await panel.waitFor({ state: "hidden" });
  }
  await openWithToggle();
  await touch("touchStart", 110); await touch("touchMove", 160); await touch("touchCancel"); await settled();
  assert.equal((await panel.boundingBox()).x, 50, "cancelled drag restores the drawer");
  await touch("touchStart", 110); await touch("touchMove", 112, 620); await touch("touchEnd"); await settled();
  assert.equal((await panel.boundingBox()).x, 50, "vertical gestures preserve the open drawer");
  await page.keyboard.press("Escape"); await panel.waitFor({ state: "hidden" });
  assert.equal(await page.locator("#conversationInput").inputValue(), "Draft survives opening details");
  await page.emulateMedia({ reducedMotion: "reduce", forcedColors: "active" });
  await openWithToggle();
  assert.equal(await panel.evaluate(element => getComputedStyle(element).transitionDuration), "0s");
  await page.keyboard.press("Escape"); await panel.waitFor({ state: "hidden" });
  assert.deepEqual(errors, []);
  console.log("PASS: compact token summaries, exact details, cache inclusion, zero/unknown, metadata-only polling, generation replacement, stable row height and narrow/mobile/dark layout");
  console.log("PASS: right drawer bounds, desktop columns, shared sidebar materials, direct toggle, outside dismissal, focus, responsive mode changes, follow-finger content/backdrop drag, cancellation, vertical scrolling, reduced motion and draft preservation");
} finally { await browser.close(); }
