param([Parameter(Mandatory=$true)][string]$BinaryDirectory,[Parameter(Mandatory=$true)][string]$ServerUrl,[Parameter(Mandatory=$true)][string]$NodeKey,[switch]$DebugOpenSSH,[switch]$Tray)
$ErrorActionPreference='Stop'
[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$env:PATHEXT=[Environment]::GetEnvironmentVariable('PATHEXT','Machine')
$env:PATH=[Environment]::GetEnvironmentVariable('PATH','Machine')+';'+[Environment]::GetEnvironmentVariable('PATH','User')
$fixture=Join-Path ([IO.Path]::GetTempPath()) ('mira-openssh-peer-'+[Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory $fixture | Out-Null
$env:MIRA_IDENTITY_FILE=Join-Path $fixture 'identity.json'
$env:MIRA_NODE_OPENSSH_DIR=''
$env:MIRA_OPENSSH_DEBUG=if($DebugOpenSSH){'1'}else{'0'}
$env:MIRA_NODE_TOKEN='';$env:CONTROL_SERVER_TOKEN=''
$config=Join-Path $fixture 'node.json'
[IO.File]::WriteAllText($config,(@{serverUrl=$ServerUrl;nodeKey=$NodeKey;identityFile=$env:MIRA_IDENTITY_FILE;appServerAutoStart=$false;allowedRoots=@();codexBinary=(Join-Path $fixture 'no-codex.exe')}|ConvertTo-Json),[Text.UTF8Encoding]::new($false))
$nodeProcess=$null
function Quote-Arg([string]$Value){
    if($Value.Length -gt 0 -and $Value -notmatch '[\s"]'){return $Value}
    return '"'+[regex]::Replace([regex]::Replace($Value,'(\\*)"','$1$1\"'),'(\\+)$','$1$1')+'"'
}
function Read-Log([string]$Path){
    $stream=[IO.File]::Open($Path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::ReadWrite)
    $reader=[IO.StreamReader]::new($stream)
    try{return $reader.ReadToEnd()}finally{$reader.Dispose()}
}
try{
    $nodeArguments=@('--config',(Quote-Arg $config))
    if($Tray){$nodeArguments=@('--tray')+$nodeArguments}
    $nodeProcess=Start-Process -FilePath (Join-Path $BinaryDirectory 'mira-node.exe') -ArgumentList $nodeArguments -PassThru -WindowStyle Hidden -RedirectStandardOutput (Join-Path $fixture 'node.out') -RedirectStandardError (Join-Path $fixture 'node.err')
    $handle=$nodeProcess.Handle
    @{type='ready';fixture=$fixture;pid=$nodeProcess.Id;user=[Security.Principal.WindowsIdentity]::GetCurrent().Name}|ConvertTo-Json -Compress
    while($null -ne ($line=[Console]::ReadLine())){
        $request=$line|ConvertFrom-Json
        if($request.op -eq 'quit'){break}
        if($request.op -eq 'logs'){
            $outPath=if($Tray){Join-Path $fixture 'logs\node.log'}else{Join-Path $fixture 'node.out'}
            @{id=$request.id;stdout=(Read-Log $outPath);stderr=(Read-Log (Join-Path $fixture 'node.err'))}|ConvertTo-Json -Compress;continue
        }
        if($request.op -eq 'probe'){
            $pidFile=Join-Path $fixture 'remote.pid';$remoteProcess=$null;$remotePid=$null
            if(Test-Path $pidFile){$remotePid=[int](Read-Log $pidFile);$remoteProcess=Get-Process -Id $remotePid -ErrorAction SilentlyContinue}
            @{id=$request.id;remotePid=$remotePid;alive=($null -ne $remoteProcess)}|ConvertTo-Json -Compress;continue
        }
        if($request.op -ne 'cli' -and $request.op -ne 'native'){throw 'Unknown test operation'}
        $info=[Diagnostics.ProcessStartInfo]::new()
        $info.FileName=Join-Path $BinaryDirectory 'mira.exe'
        $arguments=$request.args
        if($request.op -eq 'native'){
            $role=[string]$arguments[0]
            if($role -notin @('ssh','ssh-keygen','ssh-add','ssh-keyscan','ssh-sk-helper','ssh-pkcs11-helper')){throw 'Unapproved native test role'}
            $info.FileName=Join-Path $BinaryDirectory ($role+'.exe')
            $arguments=$arguments[1..($arguments.Count-1)]
        }
        $info.WorkingDirectory=$fixture
        $info.Arguments=($arguments|ForEach-Object {Quote-Arg ([string]$_)}) -join ' '
        $info.UseShellExecute=$false;$info.CreateNoWindow=$true
        $info.RedirectStandardInput=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true
        $process=[Diagnostics.Process]::new();$process.StartInfo=$info
        [void]$process.Start()
        $stdout=[IO.MemoryStream]::new();$stderr=[IO.MemoryStream]::new()
        $outTask=$process.StandardOutput.BaseStream.CopyToAsync($stdout)
        $errTask=$process.StandardError.BaseStream.CopyToAsync($stderr)
        $inputBytes=[Convert]::FromBase64String([string]$request.input)
        $process.StandardInput.BaseStream.Write($inputBytes,0,$inputBytes.Length);$process.StandardInput.Close()
        if(-not $process.WaitForExit(30000)){$process.Kill();throw 'Native Windows CLI timed out'}
        [void]$outTask.GetAwaiter().GetResult();[void]$errTask.GetAwaiter().GetResult()
        @{id=$request.id;code=$process.ExitCode;stdout=[Convert]::ToBase64String($stdout.ToArray());stderr=[Convert]::ToBase64String($stderr.ToArray())}|ConvertTo-Json -Compress
        $process.Dispose();$stdout.Dispose();$stderr.Dispose()
    }
}finally{
    if($nodeProcess -and -not $nodeProcess.HasExited){$nodeProcess.Kill();$nodeProcess.WaitForExit()}
    # This directory was generated by this invocation and contains test identities only.
    Remove-Item -LiteralPath $fixture -Recurse -Force
}
